language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
script: rake spec
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.6.2
matrix:
  fast_finish: true
  include:
    - rvm: "1.8.7"
      env: PUPPET_VERSION=2.7.26
  exclude:       
    - rvm: "2.1.1"
      env: PUPPET_VERSION=3.4.3
