language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
script: bundle exec rake all
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.6.2
matrix:
  fast_finish: true
  exclude:
    - rvm: "2.1.1"
      env: PUPPET_VERSION=3.4.3
