name    'fnerdwq-vim'
version '0.1.0'
source 'https://github.com/fnerdwq/puppet-vim.git'
author 'Frederik Wagner'
license 'Apache License, Version 2.0'
summary 'Puppet module for vim'
description 'Small vim configuration module'
project_page 'https://github.com/fnerdwq/puppet-vim'
